name: auto_CC_checkin

on:
  schedule:
    - cron: '30 16 * * *'

jobs:
  checkin:
    runs-on: ubuntu-latest
    steps:
      - uses: yanglbme/cordcloud-action@main
        with:
          email: ${{ secrets.EMAIL }}
          passwd: ${{ secrets.PASSWORD }}
          host: cordcloud.one,cordcloud.us,cordcloud.biz,c-cloud.xyz
